cal/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'cal'
urlpatterns = [
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    path('calendar/event/new/<str:datum>/', views.EventNewFromCalView.as_view(), name='new_event_from_cal'),
    url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
    path('delete_event/<int:pk>/', views.EventDeleteView.as_view(), name = 'event_delete'),
    path('list_events/<str:choice>/', views.EventChoiceListView.as_view(), name = 'event_choice_list'),
    path('event_coming_list/', views.EventComingListView.as_view(), name = 'event_coming_list'),
]

seznam_kontaktu/urls.py
from django.urls import path
from . import views

app_name = 'seznam_kontaktu'
urlpatterns = [
    path('list_contacts/', views.ContactsListView.as_view(), name = 'list_contacts'),
    path('new_contact/', views.NewContactView.as_view(), name='new_contact'),
    path('edit_contact/<int:pk>/', views.EditContactView.as_view(), name='edit_contact'),
    path('delete_contact/<int:pk>/', views.DeleteContactView.as_view(), name = 'delete_contact'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
  <title> Rodinný kalendář </title>
</head>
<body>
    {% block content %}
    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

templates/calendar.html
<!-- templates/calendar.html -->

{% extends 'base.html' %}
{% block content %}
<!--navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Přehled</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'seznam_kontaktu:list_contacts' %}">Kontakty</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'cal:event_new' %}">Založit novou událost</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'cal:calendar' %}?{{prev_month }}">Předchozí měsíc</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'cal:calendar' %}?{{next_month }}"> Další měsíc</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'cal:event_coming_list' %}"> Nejbližší události</a>
      </li>
      <li class="nav-item active dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Kategorie
        </a>
        <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
          <a class="btn btn-primary" href='{% url "cal:event_choice_list" choice="narozeniny"%}'> narozeniny</a>
          <a class="btn btn-secondary" href='{% url "cal:event_choice_list" choice="svátek"%}'> svátek</a>
          <a class="btn btn-success" href='{% url "cal:event_choice_list" choice="dovolená"%}'> dovolená</a>
          <a class="btn btn-info" href='{% url "cal:event_choice_list" choice="doctor"%}'> doctor</a>
          <br>
          <a class="btn btn-warning" href='{% url "cal:event_choice_list" choice="other"%}'> other </a>
        </div>
      </li>
      <li class="nav-item active">
        <a class="btn btn-outline-light my-2 my-sm-0" href="{% url 'logout' %}">Odhlásit</a>
      </li>
  </div>
</nav>
<!--months nav-->
  <ul class="nav nav-pills nav-fill">
    {% for i in months_for_loop %}
        <li class="nav-item active bg-dark">
            <a id ="p{{ i }}" href="" class="nav-link active bg-dark"></a>
        </li>
    {% endfor %}
  </ul>
<br>
<!--calendar table-->
<div class="container">
    {{calendar }}
</div> 
<!--JS for months nav-->
<script>
    var today = new Date();
    var i;
    for (i = 1; i < 12; i++) {
        var date = "?month=" + today.getFullYear() + '-' + (today.getMonth() + i);
        var identification = "p" + i
        document.getElementById(identification).href = date;
        document.getElementById(identification).innerHTML = today.getMonth() + i
    }
</script>
{% endblock %}

templates/event.html
<!-- templates/event.html -->
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
	Událost
{% endblock %}
{% block content %}
{% include "menu.html" %}
<br>
<div class="container">
  <form method="post">
    {% csrf_token %}
    {{form | crispy}}
    <div class='row'>
      <div class="col text-center">
        <button type="submit" class="btn btn-success btn-lg btn-block"> Uložit </button>
      </div>
    </div>
  </form>
</div>
{% endblock %}

templates/event_choice_list.html
<!-- templates/event_choice_list.html -->
{% extends 'base.html' %}
{% block content %}
{% include "menu.html" %}
<br>
<div class="container">
    {% if events.0.type_of_events %}
      <b> Vybraná kategorie: 
        <div class="{{events.0.fetch_class}}"> 
        {{ events.0.type_of_events }} 
        </div>
      </b>
    {% else %}
      <p>Ani jedna událost tohoto typu</p>
    {% endif %}
    <br><br>

  <table class="table table-sm">
    <thead>
      <tr>
        <th scope="col"> Název </th>
        <th scope="col"> Od </th>
        <th scope="col"> Do </th>
      </tr>
    </thead>
    <tbody>
      {% for i in events %}  
        <tr>
          <td> {{ i.title }} </td> 
          <td> {{ i.start_time }} </td> 
          <td scope="row"> {{ i.end_time }}</td>

        </tr>
      {% endfor %}
    </tbody>
  </table>  
</div>
{% endblock %}

templates/event_coming_list.html
<!-- templates/event_choice_list.html -->
{% extends 'base.html' %}
{% block content %}
{% include "menu.html" %}
<br>
<div class="container">
  <b>Seznam událostí:</b>
  <br><br>

  <table class="table table-sm">
    <thead>
      <tr>
        <th scope="col"> Název </th>
        <th scope="col"> Kategorie </th>
        <th scope="col"> Od </th>
        <th scope="col"> Do </th>
      </tr>
    </thead>
    <tbody>
      {% for i in coming_events %}	
        <tr>
          <td> {{ i.title }} </td> 
          <td> <div class="{{i.fetch_class}}"> {{ i.type_of_events }} </div> </td> 
          <td> {{ i.start_time }} </td> 
          <td scope="row"> {{ i.end_time }}</td>

        </tr>
      {% endfor %}
    </tbody>
  </table>  
</div>
{% endblock %}

templates/event_delete.html
<!-- templates/event_delete.html -->
{% extends 'base.html' %}
{% block content %}
	<h2>Smazání události</h2>
	<form action="" method="post">{% csrf_token %}
		<p>Určitě chceš smáznout událost "{{ event.title }} v termínu {{ event.start_time }}"?</p>
		<input class="btn btn-dark btn-lg" type="submit" value="Smáznout" />
		<a class="btn btn-dark btn-lg" href="{% url 'cal:calendar' %}"> Ne </a>
	</form>
{% endblock %}

templates/menu.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Rodinný kalendář</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'seznam_kontaktu:list_contacts' %}">Kontakty</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'cal:calendar' %}">Zpět na kalendář</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'cal:event_new' %}">Založit novou událost</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'cal:event_coming_list' %}"> Nejbližší události</a>
      </li>


      <li class="nav-item active dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Kategorie
        </a>
        <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
          <a class="btn btn-primary" href='{% url "cal:event_choice_list" choice="narozeniny"%}'> narozeniny</a>
          <a class="btn btn-secondary" href='{% url "cal:event_choice_list" choice="svátek"%}'> svátek</a>
          <a class="btn btn-success" href='{% url "cal:event_choice_list" choice="dovolená"%}'> dovolená</a>
          <a class="btn btn-info" href='{% url "cal:event_choice_list" choice="doctor"%}'> doctor</a>
          <br>
          <a class="btn btn-warning" href='{% url "cal:event_choice_list" choice="other"%}'> other </a>
        </div>
      </li>

      <li class="nav-item active">
        <a class="btn btn-outline-light my-2 my-sm-0" href="{% url 'logout' %}">Odhlásit</a>
      </li>
  </div>
</nav>

templates/not_allowed.html
Not allowed