cal/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'cal'
urlpatterns = [
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    path('calendar/event/new/<str:datum>/', views.EventNewFromCalView.as_view(), name='new_event_from_cal'),
    url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
    path('delete_event/<int:pk>/', views.EventDeleteView.as_view(), name = 'event_delete'),
    path('list_events/<str:choice>/', views.EventChoiceListView.as_view(), name = 'event_choice_list'),
    path('event_coming_list/', views.EventComingListView.as_view(), name = 'event_coming_list'),
]

seznam_kontaktu/urls.py
from django.urls import path
from . import views

app_name = 'seznam_kontaktu'
urlpatterns = [
    path('list_contacts/', views.ContactsListView.as_view(), name = 'list_contacts'),
    path('new_contact/', views.NewContactView.as_view(), name='new_contact'),
    path('edit_contact/<int:pk>/', views.EditContactView.as_view(), name='edit_contact'),
    path('delete_contact/<int:pk>/', views.DeleteContactView.as_view(), name = 'delete_contact'),
]

templates/contacts/contact.html
{% extends '../base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Nový kontakt
{% endblock %}
{% block content %}
{% include "../menu.html" %}
<br>
<div class="container">
  <form method="post">
    {% csrf_token %}
    {{form | crispy}}
    <div class='row'>
      <div class="col text-center">
        <button type="submit" class="btn btn-success btn-lg btn-block"> Uložit </button>
      </div>
    </div>
  </form>
</div>
{% endblock %}

templates/contacts/contact_delete.html
{% extends 'base.html' %}
{% block content %}
    <h2>Smazání kontaktu</h2>
    <form action="" method="post">{% csrf_token %}
        <p>Určitě chceš smáznout kontakt "{{ contact.first_name }} {{ contact.last_name }}"</p>
        <input class="btn btn-dark btn-lg" type="submit" value="Smáznout" />
        <a class="btn btn-dark btn-lg" href="{% url 'seznam_kontaktu:list_contacts' %}"> Ne </a>
    </form>
{% endblock %}

templates/contacts/contacts_list.html
{% extends '../base.html' %}
{% block content %}
{% include "../menu.html" %}
<br>
<div class="container">
  <b>Seznam kontaktů:</b>
  <br><br>
  <a class="btn btn-dark btn-md" href="{% url 'seznam_kontaktu:new_contact' %}"> Vytvořit nový kontakt </a>
  <br>
  <table class="table table-sm">
    <thead>
      <tr>
        <th scope="col"> Jméno </th>
        <th scope="col"> Příjmení </th>
        <th scope="col"> Telefonní číslo </th>
        <th scope="col"> Email </th>
        <th scope="col"> Změny </th>
      </tr>
    </thead>
    <tbody>
      {% for i in contacts %}  
        <tr>
          <td> {{ i.first_name }} </td> 
          <td> {{ i.last_name }} </div> </td> 
          <td> {{ i.phone_number}} </td> 
          <td> {{ i.email }}</td>
          <td>  <a href="{% url 'seznam_kontaktu:edit_contact' i.pk %}"> Editovat </a>
          <a href="{% url 'seznam_kontaktu:delete_contact' i.pk %}"> Smazat </a></td>


        </tr>
      {% endfor %}
    </tbody>
  </table>  
</div>
{% endblock %}